"""Regenerate the embedded mini-lexicon for rhyme-score-sandbox.html.

The sandbox is self-contained HTML (no server, no CMUdict download), so it
embeds pronunciations for the words the course actually uses as examples.
This script produces that block from the repo's own pipeline -- the same
``pronunciations_for`` every lesson number comes from -- so the widget's
syllables are the syllabifier's, not a hand transcription.

Run from the repo root and paste the output between the LEXICON markers in
``rhyme-score-sandbox.html``:

    python learning/interactive/widgets/generate_sandbox_lexicon.py

Add words to ``WORDS`` as lessons acquire new examples; missing words are
reported, not fatal (the widget's raw-ARPAbet entry covers one-offs).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from rhyme_schemer import pronunciations_for  # noqa: E402

# Every word a lesson, ledger item, or exercise uses as an example.
WORDS = """
lincoln reason listen orange season
sweaty heavy betty sweater already spaghetti ready forgetting confetti
palms arms calm bombs drop vomit nervous surface
wrote whole goes down crowd loud mouth out come run knees how now
day wake take cake shake state up great debate ate one who feeling every
sky fire higher choir
national rational cat hat time rhyme lessen strengthen
get setup plane sane man see me you to
hypnotize eyes six around empty read seed give
bird word verse first curse earth worth
choking joking flowing going groovy
""".split()


def main() -> None:
    lexicon: dict[str, list[list[dict]]] = {}
    missing: list[str] = []
    for word in WORDS:
        variants = pronunciations_for(word)
        if not variants:
            missing.append(word)
            continue
        lexicon[word] = [
            [
                {"o": list(s.onset), "n": s.nucleus, "s": int(s.stress), "c": list(s.coda)}
                for s in pron.syllables
            ]
            for pron in variants
        ]

    print(f"// {len(lexicon)} words, generated by generate_sandbox_lexicon.py -- do not hand-edit")
    print("const LEXICON = " + json.dumps(lexicon, separators=(",", ":")) + ";")
    if missing:
        print(f"// OOV, skipped: {' '.join(missing)}", file=sys.stderr)


if __name__ == "__main__":
    main()
